/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/intelligentrobotics/rokon_clone/October/src/unit/srv/for_feedback.srv
 *
 */


#ifndef UNIT_MESSAGE_FOR_FEEDBACKREQUEST_H
#define UNIT_MESSAGE_FOR_FEEDBACKREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unit
{
template <class ContainerAllocator>
struct for_feedbackRequest_
{
  typedef for_feedbackRequest_<ContainerAllocator> Type;

  for_feedbackRequest_()
    : positionx(0.0)
    , positiony(0.0)
    , angle_a4(0.0)
    , angle_a5(0.0)  {
    }
  for_feedbackRequest_(const ContainerAllocator& _alloc)
    : positionx(0.0)
    , positiony(0.0)
    , angle_a4(0.0)
    , angle_a5(0.0)  {
    }



   typedef float _positionx_type;
  _positionx_type positionx;

   typedef float _positiony_type;
  _positiony_type positiony;

   typedef float _angle_a4_type;
  _angle_a4_type angle_a4;

   typedef float _angle_a5_type;
  _angle_a5_type angle_a5;




  typedef boost::shared_ptr< ::unit::for_feedbackRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unit::for_feedbackRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct for_feedbackRequest_

typedef ::unit::for_feedbackRequest_<std::allocator<void> > for_feedbackRequest;

typedef boost::shared_ptr< ::unit::for_feedbackRequest > for_feedbackRequestPtr;
typedef boost::shared_ptr< ::unit::for_feedbackRequest const> for_feedbackRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unit::for_feedbackRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unit::for_feedbackRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace unit

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::unit::for_feedbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unit::for_feedbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unit::for_feedbackRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unit::for_feedbackRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unit::for_feedbackRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unit::for_feedbackRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unit::for_feedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "be728aef6bbb899ee65afa8258f16fed";
  }

  static const char* value(const ::unit::for_feedbackRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbe728aef6bbb899eULL;
  static const uint64_t static_value2 = 0xe65afa8258f16fedULL;
};

template<class ContainerAllocator>
struct DataType< ::unit::for_feedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unit/for_feedbackRequest";
  }

  static const char* value(const ::unit::for_feedbackRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unit::for_feedbackRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
\n\
float32 positionx\n\
float32 positiony\n\
\n\
float32 angle_a4\n\
float32 angle_a5\n\
";
  }

  static const char* value(const ::unit::for_feedbackRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unit::for_feedbackRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.positionx);
      stream.next(m.positiony);
      stream.next(m.angle_a4);
      stream.next(m.angle_a5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct for_feedbackRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unit::for_feedbackRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unit::for_feedbackRequest_<ContainerAllocator>& v)
  {
    s << indent << "positionx: ";
    Printer<float>::stream(s, indent + "  ", v.positionx);
    s << indent << "positiony: ";
    Printer<float>::stream(s, indent + "  ", v.positiony);
    s << indent << "angle_a4: ";
    Printer<float>::stream(s, indent + "  ", v.angle_a4);
    s << indent << "angle_a5: ";
    Printer<float>::stream(s, indent + "  ", v.angle_a5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNIT_MESSAGE_FOR_FEEDBACKREQUEST_H
