/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/intelligentrobotics/rokon_clone/October/src/unit/srv/from_robot.srv
 *
 */


#ifndef UNIT_MESSAGE_FROM_ROBOTRESPONSE_H
#define UNIT_MESSAGE_FROM_ROBOTRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unit
{
template <class ContainerAllocator>
struct from_robotResponse_
{
  typedef from_robotResponse_<ContainerAllocator> Type;

  from_robotResponse_()
    : command(0.0)  {
    }
  from_robotResponse_(const ContainerAllocator& _alloc)
    : command(0.0)  {
    }



   typedef float _command_type;
  _command_type command;




  typedef boost::shared_ptr< ::unit::from_robotResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unit::from_robotResponse_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct from_robotResponse_

typedef ::unit::from_robotResponse_<std::allocator<void> > from_robotResponse;

typedef boost::shared_ptr< ::unit::from_robotResponse > from_robotResponsePtr;
typedef boost::shared_ptr< ::unit::from_robotResponse const> from_robotResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unit::from_robotResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unit::from_robotResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace unit

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::unit::from_robotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unit::from_robotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unit::from_robotResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unit::from_robotResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unit::from_robotResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unit::from_robotResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unit::from_robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7a381543013b116822c4c5bfba61dfce";
  }

  static const char* value(const ::unit::from_robotResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7a381543013b1168ULL;
  static const uint64_t static_value2 = 0x22c4c5bfba61dfceULL;
};

template<class ContainerAllocator>
struct DataType< ::unit::from_robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unit/from_robotResponse";
  }

  static const char* value(const ::unit::from_robotResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unit::from_robotResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 command\n\
\n\
";
  }

  static const char* value(const ::unit::from_robotResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unit::from_robotResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.command);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct from_robotResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unit::from_robotResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unit::from_robotResponse_<ContainerAllocator>& v)
  {
    s << indent << "command: ";
    Printer<float>::stream(s, indent + "  ", v.command);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNIT_MESSAGE_FROM_ROBOTRESPONSE_H
