/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by gensrv_cpp from file /home/intelligentrobotics/rokon_clone/October/src/unit/srv/twoBall.srv
 *
 */


#ifndef UNIT_MESSAGE_TWOBALL_H
#define UNIT_MESSAGE_TWOBALL_H

#include <ros/service_traits.h>


#include <unit/twoBallRequest.h>
#include <unit/twoBallResponse.h>


namespace unit
{

struct twoBall
{

typedef twoBallRequest Request;
typedef twoBallResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct twoBall
} // namespace unit


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::unit::twoBall > {
  static const char* value()
  {
    return "7b48d08338b2f5afc2a84ccbb423f69e";
  }

  static const char* value(const ::unit::twoBall&) { return value(); }
};

template<>
struct DataType< ::unit::twoBall > {
  static const char* value()
  {
    return "unit/twoBall";
  }

  static const char* value(const ::unit::twoBall&) { return value(); }
};


// service_traits::MD5Sum< ::unit::twoBallRequest> should match 
// service_traits::MD5Sum< ::unit::twoBall > 
template<>
struct MD5Sum< ::unit::twoBallRequest>
{
  static const char* value()
  {
    return MD5Sum< ::unit::twoBall >::value();
  }
  static const char* value(const ::unit::twoBallRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::unit::twoBallRequest> should match 
// service_traits::DataType< ::unit::twoBall > 
template<>
struct DataType< ::unit::twoBallRequest>
{
  static const char* value()
  {
    return DataType< ::unit::twoBall >::value();
  }
  static const char* value(const ::unit::twoBallRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::unit::twoBallResponse> should match 
// service_traits::MD5Sum< ::unit::twoBall > 
template<>
struct MD5Sum< ::unit::twoBallResponse>
{
  static const char* value()
  {
    return MD5Sum< ::unit::twoBall >::value();
  }
  static const char* value(const ::unit::twoBallResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::unit::twoBallResponse> should match 
// service_traits::DataType< ::unit::twoBall > 
template<>
struct DataType< ::unit::twoBallResponse>
{
  static const char* value()
  {
    return DataType< ::unit::twoBall >::value();
  }
  static const char* value(const ::unit::twoBallResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // UNIT_MESSAGE_TWOBALL_H
