/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/intelligentrobotics/rokon_clone/October/src/unit/srv/twoBall.srv
 *
 */


#ifndef UNIT_MESSAGE_TWOBALLREQUEST_H
#define UNIT_MESSAGE_TWOBALLREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace unit
{
template <class ContainerAllocator>
struct twoBallRequest_
{
  typedef twoBallRequest_<ContainerAllocator> Type;

  twoBallRequest_()
    : position1x(0.0)
    , position1y(0.0)
    , position2x(0.0)
    , position2y(0.0)
    , angle_a4(0.0)
    , angle_a5(0.0)  {
    }
  twoBallRequest_(const ContainerAllocator& _alloc)
    : position1x(0.0)
    , position1y(0.0)
    , position2x(0.0)
    , position2y(0.0)
    , angle_a4(0.0)
    , angle_a5(0.0)  {
    }



   typedef float _position1x_type;
  _position1x_type position1x;

   typedef float _position1y_type;
  _position1y_type position1y;

   typedef float _position2x_type;
  _position2x_type position2x;

   typedef float _position2y_type;
  _position2y_type position2y;

   typedef float _angle_a4_type;
  _angle_a4_type angle_a4;

   typedef float _angle_a5_type;
  _angle_a5_type angle_a5;




  typedef boost::shared_ptr< ::unit::twoBallRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::unit::twoBallRequest_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct twoBallRequest_

typedef ::unit::twoBallRequest_<std::allocator<void> > twoBallRequest;

typedef boost::shared_ptr< ::unit::twoBallRequest > twoBallRequestPtr;
typedef boost::shared_ptr< ::unit::twoBallRequest const> twoBallRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::unit::twoBallRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::unit::twoBallRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace unit

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::unit::twoBallRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::unit::twoBallRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unit::twoBallRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::unit::twoBallRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unit::twoBallRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::unit::twoBallRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::unit::twoBallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9aab00efcf8e8e572d4bddea15fb584a";
  }

  static const char* value(const ::unit::twoBallRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9aab00efcf8e8e57ULL;
  static const uint64_t static_value2 = 0x2d4bddea15fb584aULL;
};

template<class ContainerAllocator>
struct DataType< ::unit::twoBallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "unit/twoBallRequest";
  }

  static const char* value(const ::unit::twoBallRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::unit::twoBallRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n\
float32 position1x\n\
float32 position1y\n\
\n\
\n\
\n\
float32 position2x\n\
float32 position2y\n\
\n\
\n\
float32 angle_a4\n\
float32 angle_a5\n\
";
  }

  static const char* value(const ::unit::twoBallRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::unit::twoBallRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.position1x);
      stream.next(m.position1y);
      stream.next(m.position2x);
      stream.next(m.position2y);
      stream.next(m.angle_a4);
      stream.next(m.angle_a5);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct twoBallRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::unit::twoBallRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::unit::twoBallRequest_<ContainerAllocator>& v)
  {
    s << indent << "position1x: ";
    Printer<float>::stream(s, indent + "  ", v.position1x);
    s << indent << "position1y: ";
    Printer<float>::stream(s, indent + "  ", v.position1y);
    s << indent << "position2x: ";
    Printer<float>::stream(s, indent + "  ", v.position2x);
    s << indent << "position2y: ";
    Printer<float>::stream(s, indent + "  ", v.position2y);
    s << indent << "angle_a4: ";
    Printer<float>::stream(s, indent + "  ", v.angle_a4);
    s << indent << "angle_a5: ";
    Printer<float>::stream(s, indent + "  ", v.angle_a5);
  }
};

} // namespace message_operations
} // namespace ros

#endif // UNIT_MESSAGE_TWOBALLREQUEST_H
