/* Software License Agreement (BSD License)
 *
 * Copyright (c) 2011, Willow Garage, Inc.
 * All rights reserved.
 *
 * Redistribution and use in source and binary forms, with or without
 * modification, are permitted provided that the following conditions
 * are met:
 *
 *  * Redistributions of source code must retain the above copyright
 *    notice, this list of conditions and the following disclaimer.
 *  * Redistributions in binary form must reproduce the above
 *    copyright notice, this list of conditions and the following
 *    disclaimer in the documentation and/or other materials provided
 *    with the distribution.
 *  * Neither the name of Willow Garage, Inc. nor the names of its
 *    contributors may be used to endorse or promote products derived
 *    from this software without specific prior written permission.
 *
 * THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS
 * "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT
 * LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS
 * FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE
 * COPYRIGHT OWNER OR CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT,
 * INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING,
 * BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES;
 * LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
 * CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
 * LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN
 * ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
 * POSSIBILITY OF SUCH DAMAGE.
 *
 * Auto-generated by genmsg_cpp from file /home/intelligentrobotics/rokon_clone/October/src/app/msg/twoBall.msg
 *
 */


#ifndef APP_MESSAGE_TWOBALL_H
#define APP_MESSAGE_TWOBALL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace app
{
template <class ContainerAllocator>
struct twoBall_
{
  typedef twoBall_<ContainerAllocator> Type;

  twoBall_()
    : pos1x(0.0)
    , pos1y(0.0)
    , pos2x(0.0)
    , pos2y(0.0)  {
    }
  twoBall_(const ContainerAllocator& _alloc)
    : pos1x(0.0)
    , pos1y(0.0)
    , pos2x(0.0)
    , pos2y(0.0)  {
    }



   typedef double _pos1x_type;
  _pos1x_type pos1x;

   typedef double _pos1y_type;
  _pos1y_type pos1y;

   typedef double _pos2x_type;
  _pos2x_type pos2x;

   typedef double _pos2y_type;
  _pos2y_type pos2y;




  typedef boost::shared_ptr< ::app::twoBall_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::app::twoBall_<ContainerAllocator> const> ConstPtr;
  boost::shared_ptr<std::map<std::string, std::string> > __connection_header;

}; // struct twoBall_

typedef ::app::twoBall_<std::allocator<void> > twoBall;

typedef boost::shared_ptr< ::app::twoBall > twoBallPtr;
typedef boost::shared_ptr< ::app::twoBall const> twoBallConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::app::twoBall_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::app::twoBall_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace app

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'app': ['/home/intelligentrobotics/rokon_clone/October/src/app/msg'], 'std_msgs': ['/opt/ros/groovy/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::app::twoBall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::app::twoBall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::app::twoBall_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::app::twoBall_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::app::twoBall_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::app::twoBall_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::app::twoBall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "10c63de25c74c1fafcc31a4c3b845873";
  }

  static const char* value(const ::app::twoBall_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x10c63de25c74c1faULL;
  static const uint64_t static_value2 = 0xfcc31a4c3b845873ULL;
};

template<class ContainerAllocator>
struct DataType< ::app::twoBall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "app/twoBall";
  }

  static const char* value(const ::app::twoBall_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::app::twoBall_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 pos1x\n\
float64 pos1y\n\
\n\
float64 pos2x\n\
float64 pos2y\n\
\n\
\n\
";
  }

  static const char* value(const ::app::twoBall_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::app::twoBall_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pos1x);
      stream.next(m.pos1y);
      stream.next(m.pos2x);
      stream.next(m.pos2y);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct twoBall_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::app::twoBall_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::app::twoBall_<ContainerAllocator>& v)
  {
    s << indent << "pos1x: ";
    Printer<double>::stream(s, indent + "  ", v.pos1x);
    s << indent << "pos1y: ";
    Printer<double>::stream(s, indent + "  ", v.pos1y);
    s << indent << "pos2x: ";
    Printer<double>::stream(s, indent + "  ", v.pos2x);
    s << indent << "pos2y: ";
    Printer<double>::stream(s, indent + "  ", v.pos2y);
  }
};

} // namespace message_operations
} // namespace ros

#endif // APP_MESSAGE_TWOBALL_H
